### PR TITLE
feat: H2のバージョンを 2.1.214 に更新しました。

### PR DESCRIPTION
**Pull request by sukegawatakashitis**
jiraチケット
https://nablarch.atlassian.net/browse/NAB-468

### CODE REVIEW

**Comment by kumagoro1202** [comment]
起動して打鍵したところシステムエラーになってしまいました。
```
2022-10-25 21:40:54.772 -FATAL- nablarch.core.log.app.FailureLogUtil [202210252140547010003] boot_proc = [] proc_sys = [nablarch-example-web] req_id = [/action/project/create] usr_id = [999999999] fail_code = [MSG99999] an unexpecte
d exception occurred.
Input Data :
null
Stack Trace Information :
org.seasar.doma.jdbc.SqlExecutionException: [DOMA2009] SQLの実行に失敗しました。
SQLファイルパス=[null]。
ログ用SQL=[insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATIO
N_OF_CORP_EXPENSES, VERSION) values (null, 'あああ', 'development', 'ss', null, null, 5, 'あああの', 'あああ', null, null, null, null, null, null, 1)]。
原因は次のものです。org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
NULL not allowed for column "PROJECT_ID"; SQL statement:
insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATION_OF_CORP_E
XPENSES, VERSION) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-214]。
根本原因は次のものです。org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
NULL not allowed for column "PROJECT_ID"; SQL statement:
insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATION_OF_CORP_E
XPENSES, VERSION) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-214]
        at org.seasar.doma.jdbc.command.ModifyCommand.execute(ModifyCommand.java:73)
        at com.nablarch.example.app.web.dao.ProjectDaoImpl.insert(ProjectDaoImpl.java:75)
        at com.nablarch.example.app.web.action.ProjectAction.create(ProjectAction.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at nablarch.fw.handler.MethodBinding$1.handle(MethodBinding.java:114)
        at nablarch.integration.doma.Transactional$TransactionalImpl.lambda$handle$0(Transactional.java:58)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:245)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiresNewInternal(LocalTransactionManager.java:152)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiresNew(LocalTransactionManager.java:138)
        at nablarch.integration.doma.Transactional$TransactionalImpl.handle(Transactional.java:53)
        at nablarch.common.web.token.BasicDoubleSubmissionHandler.handle(BasicDoubleSubmissionHandler.java:96)
        at nablarch.common.web.token.OnDoubleSubmission$Impl.handle(OnDoubleSubmission.java:105)
        at nablarch.common.web.token.OnDoubleSubmission$Impl.handle(OnDoubleSubmission.java:83)
        at nablarch.fw.handler.MethodBinding.handle(MethodBinding.java:132)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.handler.DispatchHandler.handle(DispatchHandler.java:98)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at com.nablarch.example.app.web.handler.ExampleErrorForwardHandler.handle(ExampleErrorForwardHandler.java:29)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.HttpErrorHandler.handle(HttpErrorHandler.java:47)
        at nablarch.fw.web.handler.HttpErrorHandler.handle(HttpErrorHandler.java:35)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.ForwardingHandler.handle(ForwardingHandler.java:32)
        at nablarch.fw.web.handler.ForwardingHandler.handle(ForwardingHandler.java:20)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.NormalizationHandler.handle(NormalizationHandler.java:51)
        at nablarch.fw.web.handler.NormalizationHandler.handle(NormalizationHandler.java:23)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.common.web.handler.HttpAccessLogHandler.handle(HttpAccessLogHandler.java:49)
        at nablarch.common.web.handler.HttpAccessLogHandler.handle(HttpAccessLogHandler.java:25)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.common.handler.threadcontext.ThreadContextHandler.handle(ThreadContextHandler.java:80)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.common.web.session.SessionStoreHandler.handle(SessionStoreHandler.java:112)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:35)
        at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:22)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:139)
        at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:42)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:42)
        at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:32)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.common.handler.threadcontext.ThreadContextClearHandler.handle(ThreadContextClearHandler.java:25)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.handler.HttpCharacterEncodingHandler.handle(HttpCharacterEncodingHandler.java:103)
        at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
        at nablarch.fw.web.servlet.WebFrontController.doFilter(WebFrontController.java:105)
        at nablarch.fw.web.servlet.RepositoryBasedWebFrontController.doFilter(RepositoryBasedWebFrontController.java:39)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.seasar.doma.jdbc.command.ModifyCommand.executeUpdate(ModifyCommand.java:116)
        at org.seasar.doma.jdbc.command.InsertCommand.executeInternal(InsertCommand.java:36)
        at org.seasar.doma.jdbc.command.ModifyCommand.execute(ModifyCommand.java:68)
        ... 68 more
```

**Comment by sukegawatakashitis** [comment]
> 起動して打鍵したところシステムエラーになってしまいました。
> 
> ```
> 2022-10-25 21:40:54.772 -FATAL- nablarch.core.log.app.FailureLogUtil [202210252140547010003] boot_proc = [] proc_sys = [nablarch-example-web] req_id = [/action/project/create] usr_id = [999999999] fail_code = [MSG99999] an unexpecte
> d exception occurred.
> Input Data :
> null
> Stack Trace Information :
> org.seasar.doma.jdbc.SqlExecutionException: [DOMA2009] SQLの実行に失敗しました。
> SQLファイルパス=[null]。
> ログ用SQL=[insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATIO
> N_OF_CORP_EXPENSES, VERSION) values (null, 'あああ', 'development', 'ss', null, null, 5, 'あああの', 'あああ', null, null, null, null, null, null, 1)]。
> 原因は次のものです。org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
> NULL not allowed for column "PROJECT_ID"; SQL statement:
> insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATION_OF_CORP_E
> XPENSES, VERSION) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-214]。
> 根本原因は次のものです。org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
> NULL not allowed for column "PROJECT_ID"; SQL statement:
> insert into PUBLIC.PROJECT (PROJECT_ID, PROJECT_NAME, PROJECT_TYPE, PROJECT_CLASS, PROJECT_START_DATE, PROJECT_END_DATE, CLIENT_ID, PROJECT_MANAGER, PROJECT_LEADER, USER_ID, NOTE, SALES, COST_OF_GOODS_SOLD, SGA, ALLOCATION_OF_CORP_E
> XPENSES, VERSION) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-214]
>         at org.seasar.doma.jdbc.command.ModifyCommand.execute(ModifyCommand.java:73)
>         at com.nablarch.example.app.web.dao.ProjectDaoImpl.insert(ProjectDaoImpl.java:75)
>         at com.nablarch.example.app.web.action.ProjectAction.create(ProjectAction.java:90)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at nablarch.fw.handler.MethodBinding$1.handle(MethodBinding.java:114)
>         at nablarch.integration.doma.Transactional$TransactionalImpl.lambda$handle$0(Transactional.java:58)
>         at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:245)
>         at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiresNewInternal(LocalTransactionManager.java:152)
>         at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiresNew(LocalTransactionManager.java:138)
>         at nablarch.integration.doma.Transactional$TransactionalImpl.handle(Transactional.java:53)
>         at nablarch.common.web.token.BasicDoubleSubmissionHandler.handle(BasicDoubleSubmissionHandler.java:96)
>         at nablarch.common.web.token.OnDoubleSubmission$Impl.handle(OnDoubleSubmission.java:105)
>         at nablarch.common.web.token.OnDoubleSubmission$Impl.handle(OnDoubleSubmission.java:83)
>         at nablarch.fw.handler.MethodBinding.handle(MethodBinding.java:132)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.handler.DispatchHandler.handle(DispatchHandler.java:98)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at com.nablarch.example.app.web.handler.ExampleErrorForwardHandler.handle(ExampleErrorForwardHandler.java:29)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.HttpErrorHandler.handle(HttpErrorHandler.java:47)
>         at nablarch.fw.web.handler.HttpErrorHandler.handle(HttpErrorHandler.java:35)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.ForwardingHandler.handle(ForwardingHandler.java:32)
>         at nablarch.fw.web.handler.ForwardingHandler.handle(ForwardingHandler.java:20)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.NormalizationHandler.handle(NormalizationHandler.java:51)
>         at nablarch.fw.web.handler.NormalizationHandler.handle(NormalizationHandler.java:23)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.common.web.handler.HttpAccessLogHandler.handle(HttpAccessLogHandler.java:49)
>         at nablarch.common.web.handler.HttpAccessLogHandler.handle(HttpAccessLogHandler.java:25)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.common.handler.threadcontext.ThreadContextHandler.handle(ThreadContextHandler.java:80)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.common.web.session.SessionStoreHandler.handle(SessionStoreHandler.java:112)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:35)
>         at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:22)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:139)
>         at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:42)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:42)
>         at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:32)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.common.handler.threadcontext.ThreadContextClearHandler.handle(ThreadContextClearHandler.java:25)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.handler.HttpCharacterEncodingHandler.handle(HttpCharacterEncodingHandler.java:103)
>         at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
>         at nablarch.fw.web.servlet.WebFrontController.doFilter(WebFrontController.java:105)
>         at nablarch.fw.web.servlet.RepositoryBasedWebFrontController.doFilter(RepositoryBasedWebFrontController.java:39)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
>         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
>         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 列 "PROJECT_ID" にはnull値が許されていません
>         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
>         at org.seasar.doma.jdbc.command.ModifyCommand.executeUpdate(ModifyCommand.java:116)
>         at org.seasar.doma.jdbc.command.InsertCommand.executeInternal(InsertCommand.java:36)
>         at org.seasar.doma.jdbc.command.ModifyCommand.execute(ModifyCommand.java:68)
>         ... 68 more
> ```

こちらで修正しました。
https://github.com/nablarch/nablarch-example-thymeleaf-web/pull/23/commits/197a12b00df8dda51241781951fbc8f12f2e060f

**Comment by sukegawatakashitis** [comment]
@kumagoro1202 
DEFAULT ON NULL の設定を、edmファイルでしてしまっている件を、
こちらで修正しました。
https://github.com/nablarch/nablarch-example-thymeleaf-web/pull/23/commits/b34400ba6bdebd4838b0df0fe4dbcc67ee6967e5

**Comment by kumagoro1202** [comment]
不要な.gitkeepを削除してください。

**Comment by sukegawatakashitis** [comment]
> 不要な.gitkeepを削除してください。

こちらで修正しました。
https://github.com/nablarch/nablarch-example-thymeleaf-web/pull/23/commits/070e8f9b03e1b4df4a2400a675b11d723a214a8e

**Pull request merged**
